### ISSUE TITLE
Improve identification of infix operators

### ISSUE THREAD

**Issue by gadenbuie** [rstudio/gradethis#225]
We currently maintain a list of infix operators that adjusts how the operator appears in code feedback messages. Rather than printing as `$()`, we expect to see just `$`.

https://github.com/rstudio-education/gradethis/blob/d753e54a435c9ee8d704e1b3983145eb05707555/R/utils.R#L8-L14

The above list is likely incomplete and we may be able to improve the overall function with one (or both) of the following options:

1. With a bit of work we could catalogue all operators:
	1. Source the list from `?Syntax` and the linked help pages (Arithmetic, Comparison, Control, etc.)
	2. Catch `%<name>%` style infixes with regex
3. Follow the approach in https://github.com/rstudio-education/gradethis/pull/223#discussion_r585117252:

   >If function doesn't start with an alpha char, and is a call, then it is an infix op

**Comment by rossellhayes** [comment]
Closed by #327
