### ISSUE TITLE
Place code hint in new paragraph

### ISSUE THREAD

**Issue by garrettgman** [rstudio/gradethis#242]
When feedback includes both a message and a code hint, can we place the code hint in a new paragraph with a line break between the message and the code hint? This will help the student parse the message and the code hint separately, which may lead to a deeper understanding of each.

For example, the feedback below 

<img width="443" alt="Screen Shot 2021-06-02 at 11 13 01 AM" src="https://user-images.githubusercontent.com/85014/120515434-eab0db80-c393-11eb-89ae-df3d86e2ad37.png">

would appear as

> Use ymd(), mdy(), or dmy() to turn AEENDT into a date. 
>
> Your call to mutate() should include "AEENDT" as one of its arguments. You may have misspelled an argument name, or left out an important argument. But no need to fret, try it again.

**Comment by gadenbuie** [comment]
Yes you can! You can set the `maybe_code_feedback.before` option in `gradethis_setup()` to `"\n\n"`:

```r
gradethis_setup(maybe_code_feedback.before = "\n\n")

ex <- mock_this_exercise(2, 1)
grader <- grade_this({
  pass_if_equal()
  fail("Hey, good try!", hint = TRUE)
})

grader(ex)
#> <gradethis_graded: [Incorrect]
#>   Hey, good try!
#> 
#>   I expected `1` where you wrote `2`.
#> >
```
