### ISSUE TITLE
`grade_this_code()` returns an error if `.user_code` is empty

### ISSUE THREAD

**Issue by rossellhayes** [rstudio/gradethis#262]
Possibly related to #13.

If a student submits an empty code chunk, `grade_this_code()` returns a neutral grade with an error. I would have expected either a failing grade or a neutral grade with a message explaining that the submission was empty. At the very least, the student should not see an error and the message should not state that there was a problem with the grading code.

``` r
library(gradethis)

grade_this_code()(
  mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)")
)
#> #> grade_this_code()(mock_this_exercise(.user_code = "", .solution_code = "rnorm(1)"))
#> Error in (function (e) {    on_error(e, this_env)})(structure(list(message = "Assertion on 'user_code' failed: All elements must have at least 1 characters.",     call = to_expr(user_code, "user_code")), class = c("simpleError", "error", "condition"))): Assertion on 'user_code' failed: All elements must have at least 1 characters.
#> <gradethis_graded_this_code: [Neutral]
#>   A problem occurred with the grading code for this exercise.
#> >
```

<sup>Created on 2021-10-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gadenbuie** [comment]
Move this into a helper function `.user_code <- assert_user_code(.user_code)` and call at the top of `grade_this_code()` and `grade_this()`

https://github.com/rstudio/gradethis/blob/99549b9d9a6ce74b34bf12416bbf050ab171e583/R/graded.R#L649-L655
