### ISSUE TITLE
Feature request: YAML `allow_skip: false` conditions next section to submitting correct answer

### ISSUE THREAD

**Issue by gaelso** [rstudio/gradethis#273]
Current behavior of learnr exercises with YAML `progressive: true` and `allow_skip: false` doesn't condition the access to a next section based on the code submitted. When clicking Continue / Next topic before any interaction with the exercise, the following message appears:

> You must complete the exercise in this section before continuing.

This is a bit misleading as clicking on the Run code button on any code or even on an empty console unlocks access to the next section. New feature could check if `*-check` exists. If yes lock the Continue / Next topic button until users submit the correct answer and replace the current message with:

> You must submit the correct answer to the exercise in this section before continuing.

Many online courses lock access to lessons/chapters before the exercises in the previous ones are successfully completed. 

Many thanks for the amazing work done so far.

**Comment by gadenbuie** [comment]
Thanks for the feature request @gaelso. The issue in learnr is sufficient https://github.com/rstudio/learnr/issues/616
