### ISSUE TITLE
The solution code is revealed when executed code has errors

### ISSUE THREAD

**Issue by cswclui** [rstudio/gradethis#314]
When the executed code has error, the `grade_this()` function will reveal the solution code. Please refer to the following example (I expect there should be an error message (please try again) instead of revealing my solution code)

<pre>

```{r setup, include=FALSE,message=FALSE}
library(learnr)
library(gradethis)
```

```{r task, exercise=TRUE, exercise.reveal_solution=FALSE}
1$a
```

```{r task-solution}
library(tidyverse)
glimpse(iris)
```

```{r task-check}
grade_this({
  if (.solution==.result)
    pass()
  fail("Please try again")
}
)
```

</pre>

Output:
![image](https://user-images.githubusercontent.com/218137/178277094-e7716313-1b89-46f9-b1e2-3c9d57f0cebb.png)

**Comment by gadenbuie** [comment]
You can turn off hints for individual `fail()` messages using [the `hint` argument](https://pkgs.rstudio.com/gradethis/reference/graded.html#arguments):

```r
fail("Please try again.", hint = FALSE)
```

If you'd like to disable hints on all failure messages by default, you can use the [fail.hint](https://pkgs.rstudio.com/gradethis/reference/graded.html#arguments) argument of `gradethis_setup()`, called in your `setup` chunk just after attaching gradethis:

```r
library(learnr)
library(gradethis)

gradethis_setup(fail.hint = FALSE)
```

After that, if you'd like to turn on hints for specific fail messages, you can add `hint = TRUE` to the `fail()` call.

**Comment by cswclui** [comment]
> You can turn off hints for individual `fail()` messages using [the `hint` argument](https://pkgs.rstudio.com/gradethis/reference/graded.html#arguments):
> 
> ```r
> fail("Please try again.", hint = FALSE)
> ```
> 
> If you'd like to disable hints on all failure messages by default, you can use the [fail.hint](https://pkgs.rstudio.com/gradethis/reference/graded.html#arguments) argument of `gradethis_setup()`, called in your `setup` chunk just after attaching gradethis:
> 
> ```r
> library(learnr)
> library(gradethis)
> 
> gradethis_setup(fail.hint = FALSE)
> ```
> 
> After that, if you'd like to turn on hints for specific fail messages, you can add `hint = TRUE` to the `fail()` call.

I have included the options (refer to the sample code below), but it seems it is still showing the error message . Have I missed anything?

<pre>

```{r setup, include=FALSE,message=FALSE}
library(learnr)
library(gradethis)
gradethis_setup(fail.hint = FALSE)
```

```{r task, exercise=TRUE, exercise.reveal_solution=FALSE}
1$a
```

```{r task-solution}
library(tidyverse)
glimpse(iris)
```

```{r task-check}
grade_this({
  if (.solution==.result)
    pass()
  fail("Please try again", hint = FALSE)
}
)
```

</pre>

**Comment by gadenbuie** [comment]
Thanks for reporting @cswclui! I just merged changes that ensure that the default error checker will follow the `gradethis.fail.hint` option.
