### ISSUE TITLE
Remove references to R in error message

### ISSUE THREAD

**Issue by Laura-Puckett** [rstudio/gradethis#317]
The grading message for a response that includes an error is "An error occurred with your R code", which is specific to R. 

But gradethis doesn't necessarily need to be used only for R code, so it would be useful to remove "R" from the messages.

These are the files that would need to be changed:
[gradethis/R/gradethis_error_checker.R](https://github.com/rstudio/gradethis/blob/b42f81d027b8074d8e2924e70ddb7376efc19144/R/gradethis_error_checker.R)
[gradethis/R/gradethis_setup.R](https://github.com/rstudio/gradethis/blob/6324f69f2e31dd805d4edb8cb49f96ecd2dc7a68/R/gradethis_setup.R)

I tried to submit a pull request with the changes, since they're so minor, but it looks like I don't have the correct access rights. I'd still be happy to make the changes myself if you want, but I'd need to be granted access first. 

Thanks!

**Comment by gadenbuie** [comment]
We do have an `.engine` pronoun that can likely be used in these messages, but it seems like it'd be just fine for these messages to simply say "your code"

https://github.com/rstudio/gradethis/blob/6324f69f2e31dd805d4edb8cb49f96ecd2dc7a68/R/gradethis_setup.R#L218

https://github.com/rstudio/gradethis/blob/b42f81d027b8074d8e2924e70ddb7376efc19144/R/gradethis_error_checker.R#L59-L62

**Comment by Laura-Puckett** [comment]
closed with https://github.com/rstudio/gradethis/pull/318
