### ISSUE TITLE
Disabling the code feedback via `gradethis_setup`

### ISSUE THREAD

**Issue by nischalshrestha** [rstudio/gradethis#320]
There might be situations where you don't want any code feedback. For example you would want to turn off the R code feedback when writing a lesson for a different language.

On latest version of `gradethis`: I am trying to use `gradethis::fail()` without code feedback without having to do `gradethis::fail(hint = FALSE)` every time I use it. I _should_ be able to do this by setting the global option `"gradethis.fail.hint"` to `FALSE` with [`gradethis_setup()`](https://pkgs.rstudio.com/gradethis/reference/gradethis_setup.html):

```r
gradethis::gradethis_setup(fail.hint = FALSE)
```

However, it seems like this is not working and I still get code feedback. My workaround was setting the default `fail` string:

```r
gradethis::gradethis_setup(fail = "Incorrect. {gradethis::random_encouragement()}")
```

Small reprex:

````
---
title: "Grading without feedback"
output: learnr::tutorial
runtime: shiny_prerendered
date: "2022-08-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(learnr)
library(gradethis)

# this does not seem to disable code feedback globally
gradethis::gradethis_setup(fail.hint = FALSE)

# workaround of setting default `fail` message does work
# gradethis_setup(fail = "{random_encouragement()}")
```

# Addition

```{r add, exercise=TRUE}
1 + 
```

```{r add-solution}
1 + 1
```


```{r add-check}
gradethis::grade_this({
  pass_if_equal()
  fail()
})
```
````

**Comment by gadenbuie** [comment]
There are two ways that code feedback can be added to a fail message:

1. If you ask for a hint using `hint = TRUE` in any call to `fail()` or its friends, regardless of the feedback `message`.
2. From `maybe_code_feedback()` in the default feedback `message`.

You can disable these using the options in `gradethis_setup()`:

1. `fail.hint = FALSE` sets `hint = FALSE` by default for all `fail()` and friends.
2. `maybe_code_feedback = FALSE` disables any calls to `maybe_code_feedback()` when used in any feedback `message`s, including the default message.

So in your case you could use

```r
gradethis_setup(
  fail.hint = FALSE,
  maybe_code_feedback = FALSE
)
```

to turn off code feedback everywhere other than where `hint = TRUE`.

That said, #321 will completely disable code feedback for any exercise engine other than R.
